### ISSUE TITLE
Composer doesn't work after install in Azure

### ISSUE THREAD

**Issue by lostncg** [SyntaxC4-MSFT/ComposerExtension#16]
I have 3 server with same setting, the rest was worked, but one doesn't work, I cant figure out why?
![sp170211_144423](https://cloud.githubusercontent.com/assets/11206864/22851834/f2738712-f068-11e6-8871-f4f8e5bd0e8b.png)
![sp170211_144440](https://cloud.githubusercontent.com/assets/11206864/22851835/f27904ee-f068-11e6-9eeb-864d9f410226.png)

**Comment by SyntaxC4** [comment]
I have tested this on a Free App Service Web App and not running into any issues. Could you share some more information on what you are experiencing?
