### ISSUE TITLE
Composer doesn't run when deployment is done via VSTS

### ISSUE THREAD

**Issue by UsamaAslam23** [SyntaxC4-MSFT/ComposerExtension#19]
We are using VSTS for deployment on azure via FTP/S task. In our web app, composer does not run automatically and need to be updated manually from azure. Is there a way to automate this process?
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-deploy-ftp

**Comment by SyntaxC4** [comment]
Kudu isn't invoked as part of the FTP/S process. The way to automate would be to use the new Zip deploy feature, or Web Deploy.
