### ISSUE TITLE
'composer' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by neoacevedo** [SyntaxC4-MSFT/ComposerExtension#22]
When I try to run composer from debug console or KuduExec I got the following error:
```
'composer' is not recognized as an internal or external command, operable program or batch file
```

**Comment by matfax** [comment]
It seems to be related to the PHP version. Try version 7.1 instead of 7.2.

**Comment by neoacevedo** [comment]
matfax I used PHP 7.1 in the Web App and it didn't any difference (26 Apr - 10 May). But now, is working with both PHP versions.

**Comment by anupambd94** [comment]
https://www.youtube.com/watch?v=vNmx1Za9AFM check this solution. I think this will help.

**Comment by benjamin-smith** [comment]
7.0 working as per https://stackoverflow.com/questions/43486006/failed-to-install-composer-azure-server

Should this be added to the readme?

**Comment by Reema-Mansour** [comment]
if you installed composer after opening your editor please relaunch your editor so composer will be recognized
