### ISSUE TITLE
Errors when trying to download via SVN

### ISSUE THREAD

**Issue by enricodeleo** [SyntaxC4-MSFT/ComposerExtension#5]
Hi!
I find this extension the must for every php developer willing to deploy on Azure Site, but I'm finding some problems with dependencies: sometimes happens that a dependency could not be find under git and composer tries with SVN. In this case the deployment process is being flagged as successful but it actually isn't, 'cause Azure Site doesn't support the svn command.

Have you any ideas on how to introduce the svn command?

Thanks!

**Comment by SyntaxC4** [comment]
@enricodeleo Is this something that could be achieved with git-svn? or does it have to be pure svn?

**Comment by enricodeleo** [comment]
On Linux and Mac it falls back to pure svn

**Comment by SyntaxC4** [comment]
svn isn't supported on Azure App Service at this time. ping @davidebbo.

you could also vote for svn support on the [Azure Feedback](http://feedback.azure.com) site

**Comment by enricodeleo** [comment]
Thank you @SyntaxC4! I created a suggestion on http://feedback.azure.com/forums/34192--general-feedback/suggestions/9660390-support-svn-on-azure-app-service !
