### ISSUE TITLE
Load custom PHP extensions when running composer

### ISSUE THREAD

**Issue by metaclassing** [SyntaxC4-MSFT/ComposerExtension#7]
Azure does not auto-load PHP binary extensions (such as LDAP). The user must upload their own copy of the binary (compatible for the configured version of PHP) and then either alter the website settings to load it or upload a custom .user.ini file specifying the extension=D:\path\to\wwwroot\somedir\extension.dll

Some composer install commands fail (such as Adldap/Adldap) if the interpreter running composer does not have the binary extension required for the library to operate loaded, even if the IIS invoked PHP interpreter does.

I ended up editing my deploy script to -dextension=D:\path\blah\my.dll and that resolved it temporarily however does not autoload additional libraries if the website variable or .user.ini file is updated. Is there any way the default composer extension can attempt to load additional configuration files to avoid this issue?

**Comment by SyntaxC4** [comment]
you could also use a `PHP_INI_SCAN_DIR` to provide a path to add additional extensions to the SYSTEM level php.ini (which will get loaded on both the command line and web server)

Documentation available on [Configuring PHP on Azure Web App](https://azure.microsoft.com/en-us/documentation/articles/web-sites-php-configure/)

**Comment by metaclassing** [comment]
PHP_INI_SCAN_DIR was one of the solutions I tested, it did not appear to load anything for the CLI environment, only the webserver. phpinfo(); from http showed the module loaded while the CLI php interpreter was still unaware.

**Comment by SyntaxC4** [comment]
Can you share the ini file that you placed in the scan dir?

**Comment by metaclassing** [comment]
Sure, this is the complete contents of extensions.ini which was placed in the scan dir:                                                                                                           

```
; Enable Extensions
extension=D:\home\site\wwwroot\bin\php_ldap.dll
```

The included DLL file is part of the deployed package and corresponds with the configured version of PHP for this Azure website. It worked fine when I specified the manual path to include via the CLI.

**Comment by peterpostmann** [comment]
Using PHP_INI_SCAN_DIR with extensions.ini solved the problem for me. PHP_EXTENSIONS still doesnt work for the CLI environment.
